Ad renewal letters - Create record first
DEFRA/waste-exemptions-back-office pull request #386
Opened 2019-09-12 12:57 UTC by cintamani

This refactoring includes:
 - Rake task to use a `letters` namespace so that we can reuse it for other letters exports
 - We decided to create the export letters record first and update it with failure or success info later. This will make it easier to create a button in the backend that can re-run the job based on the record.
 - Everything run around the expires_on date: that is what determine the correct content and date of a given bulk document

2019-09-12 16:14 UTC, Cruikshanks approved these changes

2019-09-12 16:23 UTC, Cruikshanks requested changes

2019-09-12 16:23 UTC, Cruikshanks commented on lib/tasks/letters.rake
> +  namespace :export do
Could we tweak the namespace name to be `:generate`? This will then make it consistent with the reports rake task.

2019-09-13 08:24 UTC, cintamani commented on lib/tasks/letters.rake
> +  namespace :export do
As discussed in slack, I'll open a separate PR for renaming the `reports` stuff instead to use `export` and renaming the `reports` scope to `data`

2019-09-13 10:44 UTC, Cruikshanks approved these changes
🍾 🎉

2019-09-13 10:50 UTC, merged