[1876] Back Office relabel operator name on registration lookup
DEFRA/waste-exemptions-back-office pull request #838
Opened 2022-05-12 17:12 UTC by d-a-v-e

https://eaflood.atlassian.net/browse/RUBY-1875

2022-05-13 12:49 UTC, kennyevil approved these changes, later dismissed

2022-05-13 14:00 UTC, PaulDoyle-DEFRA commented on app/helpers/dashboards_helper.rb
> +    if %w[limitedCompany limitedLiabilityPartnership].include?(registration.business_type)
Please use i18n here

2022-05-13 14:01 UTC, PaulDoyle-DEFRA requested changes
Please use i18n for the labels.

2022-05-16 15:38 UTC, d-a-v-e commented
FYI @PaulDoyle-DEFRA this won't pass until https://github.com/DEFRA/waste-exemptions-engine/pull/671 is merged. Alternatively I can duplicate the method this relies on in `app/models/waste_exemptions_engine/registration.rb`

2022-05-18 12:08 UTC, PaulDoyle-DEFRA approved these changes

2022-05-18 12:23 UTC, merged